apiVersion: v1
kind: Pod
metadata:
  name: cfg
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh", "-c", "env | grep -E 'LOG|FEAT|DB_'; ls /etc/cfg; sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-cfg
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-cred
          key: DB_PASSWORD
    volumeMounts:
    - name: cfg
      mountPath: /etc/cfg
      readOnly: true
  volumes:
  - name: cfg
    configMap:
      name: app-cfg
