apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-grafana-admin.yaml
- ingress-nginx-metrics.yaml
- servicemonitors.yaml
- slo-rules.yaml
- dashboards/lab-visitors.yaml
- dashboards/lab-internals.yaml
- dashboards/lab-chaos.yaml
