---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCj0xsx+lHOzGVGMtPNFzKa++0oJkYoowzRL4yZviFqpNXXxmSFhlJuDqgrd6938ELJT8dUB5yuOd+XYUASNLDX4ZqNOCcI93HajhthVWo/mZedj3sj2Kc+2HZfKOzCMh0swNWCILMuNAL1mCuYEnTW4QBS37n15nobDR5wJipGU1F0M2Jh3ngpQJOBECh5fDzGKLb1S0YabZDdeGr3xVLGoRA8MTQWj/PAryNFH1SE2lCuLK4ScO3eDNGgMM2MsMvtySag3MWkFvnRmG+SqVTUPhDKgDUp2e3Ke2DLKNxnnScBtvZaugecwFS/RAJeG2D+cpUlAxuwtylTRCB1YZeSwdQdZGSvOYHuK8VI3KoQHa4W5pc1dBtvkKTXVWsumHSEz+5/XCjbGiOJmleB88qdG7MUrwQzM4bAad6dw+zok7KDpdoE1ZwCJ1+uTFqH0jRv8+mrI9oxB4V145iTaRZXFVYY13+Hv60YYwksz6BAdRVgJE8oT9HL/OYLLbEZv4NPSsEh18P7aRPoaiwG3EgEkQDw/LVsvKl0M+GacDTM/dxdRjNiAPP8/bre4dFCOx5472ShpUJLdgw+KPzy9+6VFigfXwT1+MaTMjjasqLdwhtJ8/MM99sXFDLK+JL9mtyq8VpqKgEwYviSJHRt1gGmDyWJCKZ+Ls5qd/qm0gLYb+qFbsroWxLLDiYVjOasvqS18dHvBpU+EdMoD8I=
    admin-user: AgCogec4G8y2Be85DJH6py7lfcQZt7V9ghDOe3Yhh9Uq3qvQrVv/4+BuHH6SMntxXODy1bBg8a+yWIcuZbKvWlLdkLdPyBVhZ9v76DMokP75NbB/uebhUJqcFvjYxtAxmnIQ5SiZ0cX4/c1xME72KACtYhclu669LNqXrzn17lWf4JWEQKo8J8VevOJlVxdLr1Yi2ffTR+CLZCCZsWdNNmuKIufRo2qia5Gf3thAdPZGLMrgqWv3k2julvzTCggxr0dwu1P+j9tB1AvEwB4H9FvH9geKVtK5fLOOhQtynx3W3XkD/AKbQnZF6wss6fkVe6db+1T1aEWoD5DYuY6VLzkeNliVSx4yp/mn4OiTB0NMGp02oX0akkiP16oo2x/bpVfATsjv/geOTFGVXiZxYvoxW8fWFVVcHn6Jw07cqjELMLZJp5KiAlvhGk5eJR38JgzmkT7t5HLnkARKRbOs0ZS4vR/ORfWxEQzmCYEtkqIxFvfTEyAF4PqEeg1s4yaVNdQTUP7Z55/EibEON+kXhJif3+W9Abjd8JhZZ7HkgsQBHklAGhAcUtIyohBiMWWY6U/o3+c3dYw4PzpfkImAo+wju0WKh6SZOxLpTzYOCI+KnG55sdlsuFglscM1JZDAsoNswTL0I/sfTBuPG3ahpX/fKj1Dzo/97Nvg0D6pXbWh1vPWeeWQCp8aHvYi3PObO6z+T5BTZA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
