apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:                       # everything the "platform" app owns
- namespaces.yaml
- quotas.yaml
- sealed-cloudflared-token.yaml
- cloudflared.yaml
