apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clinic
resources:
- guardrails.yaml
- sealed-clinic-db.yaml
- sealed-clinic-internal.yaml
- migrate-job.yaml
- api.yaml
- worker.yaml
- report-cronjob.yaml
- web.yaml
- ingress.yaml
- networkpolicies.yaml
- rbac-viewer.yaml
- rbac-chaos.yaml
